# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

# Aliases for commands. The keys of the given dictionary are the
# aliases, while the values are the commands they map to.
# Type: Dict
c.editor.command = ["urxvt","-e","vim", "-f", "{file}", "-c", "normal {line}G{column0}l"]
c.aliases = {
        'w'     : 'session-save',
        'q'     : 'quit',
        'wq'    : 'quit --save',
        }

#'cow'   : '.ceng.metu.edu.tr',
#'github': 'open github.com',
#'mygithub' : 'open github.com/koluacik',
#'weather': 'open https://duckduckgo.com/?q=weather&ia=weather',
#'currency': 'open https://www.doviz.com/',
#'odtuclass': 'open https://odtuclass.metu.edu.tr/',
#'reddit': 'open www.reddit.com',
#'fb'    : 'open www.facebook.com',
#'yt'    : 'open www.youtube.com',
#'120'   : 'open http://ma120.math.metu.edu.tr/',
#'260'   : 'open http://ma260.math.metu.edu.tr/',
#'yemek' : 'open http://kafeterya.metu.edu.tr/',
#'student': 'open https://student.metu.edu.tr/',
# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'file://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')

# Position of the tab bar.
# Type: Position
# Valid values:
#   - top
#   - bottom
#   - left
#   - right
c.tabs.position = 'top'

# When to show the tab bar.
# Type: String
# Valid values:
#   - always: Always show the tab bar.
#   - never: Always hide the tab bar.
#   - multiple: Hide the tab bar if only one tab is open.
#   - switching: Show the tab bar when switching tabs.
c.tabs.show = 'multiple'

# Duration (in milliseconds) to show the tab bar before hiding it when
# tabs.show is set to 'switching'.
# Type: Int
c.tabs.show_switching_delay = 800

# Open a new window for every tab.
# Type: Bool
c.tabs.tabs_are_windows = False

# Search engines which can be used via the address bar. Maps a search
# engine name (such as `DEFAULT`, or `ddg`) to a URL with a `{}`
# placeholder. The placeholder will be replaced by the search term, use
# `{{` and `}}` for literal `{`/`}` signs. The search engine named
# `DEFAULT` is used when `url.auto_search` is turned on and something
# else than a URL was entered to be opened. Other search engines can be
# used by prepending the search engine name to the search term, e.g.
# `:open google qutebrowser`.
# Type: Dict
c.url.searchengines = {
        'DEFAULT': 'https://duckduckgo.com/?q={}',
        'aw': 'https://wiki.archlinux.org/?search={}',
        'yt': 'https://www.youtube.com/results?search_query={}',
        'yd': 'https://duckduckgo.com/?q={}&iar=videos&iax=videos&ia=videos',
        '4': 'https://4chan.org/{}',
        '8': 'https://8ch.net/{}',
        'enwk': 'https://en.wikipedia.org/?search={}',
        'trwk': 'https://tr.wikipedia.org/?search={}',
        'aur': 'https://aur.archlinux.org/packages/?O=0&K={}',
        'img': 'https://duckduckgo.com/?q={}&iar=images&iax=images&ia=images',
        'reddt' : 'https://www.reddit.com/r/{}',
        'yemekad': 'http://kafeterya.metu.edu.tr/tarih/{}',
        'aps' : 'https://www.archlinux.org/packages/?q={}',
        'dict' : 'https://www.dictionary.com/browse/{}',
        'thes' : 'https://www.thesaurus.com/browse/{}',
        'abb' : 'https://www.abbreviations.com/{}',
        'enwd': 'https://en.wiktionary.org/wiki/{}',
        'trwd': 'https://tr.wiktionary.org/wiki/{}',
        }

# Font used for the debugging console.
# Type: QtFont
c.fonts.debug_console = '10pt monospace'

# Font used for the downloadbar.
# Type: Font
c.fonts.downloads = '10pt monospace'

# Font used for the hints.
# Type: Font
c.fonts.hints = 'bold 10pt monospace'

# Font used in the keyhint widget.
# Type: Font
c.fonts.keyhint = '10pt DejaVu Sans'

# Font used for prompts.
# Type: Font
c.fonts.prompts = '10pt DejaVu Sans'

# Font used in the statusbar.
# Type: Font
c.fonts.statusbar = '10pt DejaVu Sans'

# Font used in the tab bar.
# Type: QtFont
c.fonts.tabs = '10pt DejaVu Sans'

# Font family for cursive fonts.
# Type: FontFamily
c.fonts.web.family.cursive = None

##bindings
config.bind('<Ctrl-Shift-E>', 'edit-command',mode='command')
config.bind(';l', 'hint links yank')
config.bind(';:', 'hint images download')
config.bind(',D', 'set downloads.location.directory /home/deniz/Documents/')
config.bind(',ddo', 'set downloads.location.directory /home/deniz/Documents/Downloads')
config.bind(',dD', 'set downloads.location.directory /home/deniz/Documents/Ders')
config.bind(',dP', 'set downloads.location.directory /home/deniz/Documents/Pictures')
config.bind(',dpm', 'set downloads.location.directory /home/deniz/Documents/Pictures/memes')
config.bind('<Ctrl-Shift-D>', 'open qute://bookmarks')

c.content.headers.user_agent = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36'
