# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

# Aliases for commands. The keys of the given dictionary are the
# aliases, while the values are the commands they map to.
# Type: Dict
c.editor.command = ["urxvt","-e","nvim", "-f", "{file}", "-c", "normal {line}G{column0}l"]
c.aliases = {
        'w'     : 'session-save',
        'q'     : 'quit',
        'wq'    : 'quit --save',
        }

#'cow'   : '.ceng.metu.edu.tr',
#'github': 'open github.com',
#'mygithub' : 'open github.com/koluacik',
#'weather': 'open https://duckduckgo.com/?q=weather&ia=weather',
#'currency': 'open https://www.doviz.com/',
#'odtuclass': 'open https://odtuclass.metu.edu.tr/',
#'reddit': 'open www.reddit.com',
#'fb'    : 'open www.facebook.com',
#'yt'    : 'open www.youtube.com',
#'120'   : 'open http://ma120.math.metu.edu.tr/',
#'260'   : 'open http://ma260.math.metu.edu.tr/',
#'yemek' : 'open http://kafeterya.metu.edu.tr/',
#'student': 'open https://student.metu.edu.tr/',
# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'file://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')

# Position of the tab bar.
# Type: Position
# Valid values:
#   - top
#   - bottom
#   - left
#   - right
c.tabs.position = 'top'

# When to show the tab bar.
# Type: String
# Valid values:
#   - always: Always show the tab bar.
#   - never: Always hide the tab bar.
#   - multiple: Hide the tab bar if only one tab is open.
#   - switching: Show the tab bar when switching tabs.
c.tabs.show = 'multiple'

# Duration (in milliseconds) to show the tab bar before hiding it when
# tabs.show is set to 'switching'.
# Type: Int
c.tabs.show_switching_delay = 800

# Open a new window for every tab.
# Type: Bool
c.tabs.tabs_are_windows = False

# Search engines which can be used via the address bar. Maps a search
# engine name (such as `DEFAULT`, or `ddg`) to a URL with a `{}`
# placeholder. The placeholder will be replaced by the search term, use
# `{{` and `}}` for literal `{`/`}` signs. The search engine named
# `DEFAULT` is used when `url.auto_search` is turned on and something
# else than a URL was entered to be opened. Other search engines can be
# used by prepending the search engine name to the search term, e.g.
# `:open google qutebrowser`.
# Type: Dict
c.url.searchengines = {
        'DEFAULT': 'https://duckduckgo.com/?q={}',
        'aw': 'https://wiki.archlinux.org/?search={}',
        'yt': 'https://www.youtube.com/results?search_query={}',
        'yd': 'https://duckduckgo.com/?q={}&iar=videos&iax=videos&ia=videos',
        '4': 'https://4chan.org/{}',
        '8': 'https://8ch.net/{}',
        'enwk': 'https://en.wikipedia.org/?search={}',
        'trwk': 'https://tr.wikipedia.org/?search={}',
        'aur': 'https://aur.archlinux.org/packages/?O=0&K={}',
        'img': 'https://duckduckgo.com/?q={}&iar=images&iax=images&ia=images',
        'reddt' : 'https://www.reddit.com/r/{}',
        'yemekad': 'http://kafeterya.metu.edu.tr/tarih/{}',
        'aps' : 'https://www.archlinux.org/packages/?q={}',
        'dict' : 'https://www.dictionary.com/browse/{}',
        'thes' : 'https://www.thesaurus.com/browse/{}',
        'abb' : 'https://www.abbreviations.com/{}',
        'enwd': 'https://en.wiktionary.org/wiki/{}',
        'trwd': 'https://tr.wiktionary.org/wiki/{}',
        }

# Font used for the debugging console.
# Type: QtFont
c.fonts.debug_console = '10pt monospace'

# Font used for the downloadbar.
# Type: Font
c.fonts.downloads = '10pt monospace'

# Font used for the hints.
# Type: Font
c.fonts.hints = 'bold 10pt monospace'

# Font used in the keyhint widget.
# Type: Font
c.fonts.keyhint = '10pt DejaVu Sans'

# Font used for prompts.
# Type: Font
c.fonts.prompts = '10pt DejaVu Sans'

# Font used in the statusbar.
# Type: Font
c.fonts.statusbar = '10pt DejaVu Sans'

# Font used in the tab bar.
# Type: QtFont
c.fonts.tabs = '10pt DejaVu Sans'

# Font family for cursive fonts.
# Type: FontFamily
c.fonts.web.family.cursive = None

##bindings
config.bind('<Ctrl-Shift-E>', 'edit-command',mode='command')
config.bind(';l', 'hint links yank')
config.bind(';:', 'hint images download')
config.bind('<Ctrl-Shift-D>', 'open qute://bookmarks')

#proxy
config.bind('\po', 'set content.proxy socks://localhost:9090')
config.bind('\pp', 'set content.proxy system')
config.bind('\ddf', 'spawn --user prompt_download.sh')
config.bind('\ddd', 'spawn --user dmenu_download.sh')
config.bind('\ddg', 'spawn --user dmenu_download_no_name.sh')


c.content.headers.user_agent = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36'

##https://colourco.de/freebuild/292d3e-444267-32374d-676e95-8796b0-959dcb-959dcb-ffffff
##https://colourco.de/freebuild/f07178-f78c6c-ffcb6b-c3e88d-89ddff-82aaff-c792ea-ff5370
##base16 theme here,
base00 = "#292D3E"
base01 = "#444267"
base02 = "#32374D"
base03 = "#676E95"
base04 = "#8796B0"
base05 = "#959DCB"
base06 = "#959DCB"
base07 = "#FFFFFF"
base08 = "#F07178"
base09 = "#F78C6C"
base0A = "#FFCB6B"
base0B = "#C3E88D"
base0C = "#89DDFF"
base0D = "#82AAFF"
base0E = "#C792EA"
base0F = "#FF5370"

# set qutebrowser colors

# Text color of the completion widget. May be a single color to use for
# all columns or a list of three colors, one for each column.
c.colors.completion.fg = base0A

# Background color of the completion widget for odd rows.
c.colors.completion.odd.bg = base01

# Background color of the completion widget for even rows.
c.colors.completion.even.bg = base00

# Foreground color of completion widget category headers.
c.colors.completion.category.fg = base0B

# Background color of the completion widget category headers.
c.colors.completion.category.bg = base00

# Top border color of the completion widget category headers.
c.colors.completion.category.border.top = base00

# Bottom border color of the completion widget category headers.
c.colors.completion.category.border.bottom = base00

# Foreground color of the selected completion item.
c.colors.completion.item.selected.fg = base01

# Background color of the selected completion item.
c.colors.completion.item.selected.bg = base0A

# Top border color of the selected completion item.
c.colors.completion.item.selected.border.top = base0A

# Bottom border color of the selected completion item.
c.colors.completion.item.selected.border.bottom = base0A

# Foreground color of the matched text in the selected completion item.
c.colors.completion.item.selected.match.fg = base08

# Foreground color of the matched text in the completion.
c.colors.completion.match.fg = base0B

# Color of the scrollbar handle in the completion view.
c.colors.completion.scrollbar.fg = base05

# Color of the scrollbar in the completion view.
c.colors.completion.scrollbar.bg = base00

# Background color for the download bar.
c.colors.downloads.bar.bg = base00

# Color gradient start for download text.
c.colors.downloads.start.fg = base00

# Color gradient start for download backgrounds.
c.colors.downloads.start.bg = base0A

# Color gradient end for download text.
c.colors.downloads.stop.fg = base00

# Color gradient stop for download backgrounds.
c.colors.downloads.stop.bg = base0B

# Foreground color for downloads with errors.
c.colors.downloads.error.fg = base00

# Font color for hints.
c.colors.hints.fg = base00

# Background color for hints. Note that you can use a `rgba(...)` value
# for transparency.
c.colors.hints.bg = base0A

# Font color for the matched part of hints.
c.colors.hints.match.fg = base05

# Text color for the keyhint widget.
c.colors.keyhint.fg = base05

# Highlight color for keys to complete the current keychain.
c.colors.keyhint.suffix.fg = base05

# Background color of the keyhint widget.
c.colors.keyhint.bg = base00

# Foreground color of an error message.
c.colors.messages.error.fg = base00

# Background color of an error message.
c.colors.messages.error.bg = base08

# Border color of an error message.
c.colors.messages.error.border = base08

# Foreground color of a warning message.
c.colors.messages.warning.fg = base00

# Background color of a warning message.
c.colors.messages.warning.bg = base0E

# Border color of a warning message.
c.colors.messages.warning.border = base0E

# Foreground color of an info message.
c.colors.messages.info.fg = base05

# Background color of an info message.
c.colors.messages.info.bg = base00

# Border color of an info message.
c.colors.messages.info.border = base00

# Foreground color for prompts.
c.colors.prompts.fg = base05

# Border used around UI elements in prompts.
c.colors.prompts.border = base00

# Background color for prompts.
c.colors.prompts.bg = base00

# Background color for the selected item in filename prompts.
c.colors.prompts.selected.bg = base0A

# Foreground color of the statusbar.
c.colors.statusbar.normal.fg = base0B

# Background color of the statusbar.
c.colors.statusbar.normal.bg = base00

# Foreground color of the statusbar in insert mode.
c.colors.statusbar.insert.fg = base00

# Background color of the statusbar in insert mode.
c.colors.statusbar.insert.bg = base0D

# Foreground color of the statusbar in passthrough mode.
c.colors.statusbar.passthrough.fg = base00

# Background color of the statusbar in passthrough mode.
c.colors.statusbar.passthrough.bg = base0C

# Foreground color of the statusbar in private browsing mode.
c.colors.statusbar.private.fg = base00

# Background color of the statusbar in private browsing mode.
c.colors.statusbar.private.bg = base03

# Foreground color of the statusbar in command mode.
c.colors.statusbar.command.fg = base05

# Background color of the statusbar in command mode.
c.colors.statusbar.command.bg = base00

# Foreground color of the statusbar in private browsing + command mode.
c.colors.statusbar.command.private.fg = base05

# Background color of the statusbar in private browsing + command mode.
c.colors.statusbar.command.private.bg = base00

# Foreground color of the statusbar in caret mode.
c.colors.statusbar.caret.fg = base00

# Background color of the statusbar in caret mode.
c.colors.statusbar.caret.bg = base0E

# Foreground color of the statusbar in caret mode with a selection.
c.colors.statusbar.caret.selection.fg = base00

# Background color of the statusbar in caret mode with a selection.
c.colors.statusbar.caret.selection.bg = base0D

# Background color of the progress bar.
c.colors.statusbar.progress.bg = base0D

# Default foreground color of the URL in the statusbar.
c.colors.statusbar.url.fg = base05

# Foreground color of the URL in the statusbar on error.
c.colors.statusbar.url.error.fg = base08

# Foreground color of the URL in the statusbar for hovered links.
c.colors.statusbar.url.hover.fg = base05

# Foreground color of the URL in the statusbar on successful load
# (http).
c.colors.statusbar.url.success.http.fg = base0C

# Foreground color of the URL in the statusbar on successful load
# (https).
c.colors.statusbar.url.success.https.fg = base0B

# Foreground color of the URL in the statusbar when there's a warning.
c.colors.statusbar.url.warn.fg = base0E

# Background color of the tab bar.
c.colors.tabs.bar.bg = base00

# Color gradient start for the tab indicator.
c.colors.tabs.indicator.start = base0D

# Color gradient end for the tab indicator.
c.colors.tabs.indicator.stop = base0C

# Color for the tab indicator on errors.
c.colors.tabs.indicator.error = base08

# Foreground color of unselected odd tabs.
c.colors.tabs.odd.fg = base00

# Background color of unselected odd tabs.
c.colors.tabs.odd.bg = base05

# Foreground color of unselected even tabs.
c.colors.tabs.even.fg = base00

# Background color of unselected even tabs.
c.colors.tabs.even.bg = base05

# Background color of pinned unselected even tabs.
c.colors.tabs.pinned.even.bg = base05

# Foreground color of pinned unselected even tabs.
c.colors.tabs.pinned.even.fg = base00

# Background color of pinned unselected odd tabs.
c.colors.tabs.pinned.odd.bg = base05

# Foreground color of pinned unselected odd tabs.
c.colors.tabs.pinned.odd.fg = base00

# Background color of pinned selected even tabs.
c.colors.tabs.pinned.selected.even.bg = base00

# Foreground color of pinned selected even tabs.
c.colors.tabs.pinned.selected.even.fg = base05

# Background color of pinned selected odd tabs.
c.colors.tabs.pinned.selected.odd.bg = base00

# Foreground color of pinned selected odd tabs.
c.colors.tabs.pinned.selected.odd.fg = base05

# Foreground color of selected odd tabs.
c.colors.tabs.selected.odd.fg = base05

# Background color of selected odd tabs.
c.colors.tabs.selected.odd.bg = base00

# Foreground color of selected even tabs.
c.colors.tabs.selected.even.fg = base05

# Background color of selected even tabs.
c.colors.tabs.selected.even.bg = base00

# Background color for webpages if unset (or empty to use the theme's
# color).
# c.colors.webpage.bg = base00
