#TODO: tidy up this mess
i3-msg rename workspace 1 to 10
intel-virtual-output
~/Documents/miscconfs/xstuff/screen.sh #generated by arandr
~/.config/polybar/alternative_launch.sh & disown #polybar script
exit
